job/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vacancy/', include('vacancy.urls', namespace='app'))
]

vacancy/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'vacancy'

urlpatterns = (
    path('', views.all_vacancies, name='all_vacancies'),
    path('<int:id>',
         views.vacancy_detail,
         name='vacancy_details'),
)

vacancy/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Product(models.Model):
    title = models.TextField(
        max_length=255,
        verbose_name='title',
    )
    company = models.TextField(
        max_length=255,
        verbose_name='company',
    )
    date = models.DateField(
        verbose_name='date',

    )
    link = models.URLField(
        max_length=255,
        verbose_name='link',
        unique=True,
    )

    def __str__(self):
        return f'{self.id} {self.title} {self.company} {self.date} {self.link}'

    def get_absolute_url(self):
        return reverse('vacancy:vacancy_details',
                       args=[self.id])

vacancy/forms.py
from django import forms

from .models import Product

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = (
            'title',
            'company',
            'date',
            'link',
        )
        widgets = {
            'title': forms.TextInput,
            'company': forms.TextInput,
            'date': forms.TextInput,
        }

vacancy/views.py
from django.shortcuts import render, get_object_or_404

from . import models


def all_vacancies(request):
    vacancies_list = models.Product.objects.all()
    return render(request,
                  'vacancies/all_vacancies.html',
                  {'vacancies': vacancies_list})

def vacancy_detail(request, id):
    vacancy = get_object_or_404(models.Product,
                                id=id,
                                )
    return render(request,
                  'vacancies/detail.html',
                  {'vacancy': vacancy})

vacancy/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} DEFAULT TITLE {% endblock %}</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet">
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

vacancy/templates/vacancies/all_vacancies.html
{% extends "base.html" %}

{% block title %}
Vacancies list
{% endblock %}

{% block content %}
    <h1>Vacancies Python</h1>

    {% for vacancy in vacancies %}

        <h2>
            <a href="{{ vacancy.get_absolute_url }}">
                {{ vacancy.id }}    {{ vacancy.title }}
            </a>
        </h2>
        <p>
            {{ vacancy.company }}<br>{{ vacancy.date }}<br>{{ vacancy.link }}
        </p>
        <p>
            {{ vacancy.body|linebreaks }}
        </p>

    {% endfor %}

{% endblock %}

vacancy/templates/vacancies/detail.html
{% extends "base.html" %}

{% block title %} {{ vacancy.id }} {{ vacancy.title }} {% endblock %}

{% block content %}
     <a href="{% url "app:all_vacancies" %}">ALL VACANCIES</a>
     <h1>{{ vacancy.id }} {{ vacancy.title }}</h1>
     <p>
         {{ vacancy.body|linebreaks }}
     </p>

     <i>
          {{ vacancy.company|linebreaks }} {{ vacancy.date }} {{ vacancy.link|linebreaks }}
     </i>

{% endblock %}